<?php

namespace EasygestionBundle\Repository;

/**
 * ConsultantInformationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultantInformationsRepository extends \Doctrine\ORM\EntityRepository
{

}
