<?php

namespace EasygestionBundle\Repository;

/**
 * FraisIaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisIaRepository extends \Doctrine\ORM\EntityRepository
{
}
