<?php

namespace EasygestionBundle\Repository;

/**
 * IaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IaRepository extends \Doctrine\ORM\EntityRepository
{
}
