<?php

namespace EasygestionBundle\Repository;

/**
 * WorkTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
