easygestion_homepage:
    path:     /
    defaults: { _controller: EasygestionBundle:Accueil:accueil }

easygestion_login:
    path:     /login
    defaults: { _controller: EasygestionBundle:Log:login }
    
easygestion_directeur:
    path:     /directeur
    defaults: { _controller: EasygestionBundle:Directeur:directeur }

easygestion_ia:
    path:     /ia
    defaults: { _controller: EasygestionBundle:Ia:ia }
    
easygestion_mesequipes:
    path:     /mesequipes
    defaults: { _controller: EasygestionBundle:Ia:mesequipes }