easygestion_homepage:
    path:     /
    defaults: { _controller: EasygestionBundle:Accueil:accueil }

easygestion_login:
    path:     /login
    defaults: { _controller: EasygestionBundle:Log:login }
    
easygestion_directeur:
    path:     /directeur
    defaults: { _controller: EasygestionBundle:Directeur:directeur }

easygestion_ia:
    path:     /ia
    defaults: { _controller: EasygestionBundle:Ia:accueil }

easygestion_mesbesoins:
    path:     /ia/besoin
    defaults: { _controller: EasygestionBundle:Mesbesoins:mesbesoins }
    
easygestion_ajout_besoin:
    path:     /ajoutbesoin
    defaults: { _controller: EasygestionBundle:Gestion:ajout }

easygestion_team:
    path:     /team
    defaults: { _controller: EasygestionBundle:Ia:team }

easygestion_projects:
    path:     /projects
    defaults: { _controller: EasygestionBundle:Ia:projects }