easygestion_homepage:
    path:     /
    defaults: { _controller: EasygestionBundle:Accueil:accueil }

easygestion_login:
    path:     /login
    defaults: { _controller: EasygestionBundle:Log:login }

#-----------------------------------#
# Partie Gestion des besoins Julien #
#-----------------------------------#
easygestion_gestion:
    path:     /gestion
    defaults: { _controller: EasygestionBundle:Gestion:show }

#-------------------------------#
# Partie Gestion des besoins IA #
#-------------------------------#
easygestion_ia:
    path:     /ia
    defaults: { _controller: EasygestionBundle:Ia:accueil }

easygestion_mesbesoins:
    path:     /ia/besoin
    defaults: { _controller: EasygestionBundle:Mesbesoins:mesbesoins }
    
easygestion_mesbesoins_add:
    path:     /ia/besoin/add
    defaults: { _controller: EasygestionBundle:Mesbesoins:add }

easygestion_mesbesoins_archive:
    path:     /ia/besoin/archive/{id}
    defaults: { _controller: EasygestionBundle:Mesbesoins:archive }

easygestion_mesbesoins_edit:
    path:     /ia/besoin/edit/{id}
    defaults: { _controller: EasygestionBundle:Mesbesoins:edit }

#---------------------------#
# Partie Gestion des client #
#---------------------------#
easygestion_clients:
    path:     /client
    defaults: { _controller: EasygestionBundle:Client:clients }
    
easygestion_clients_add:
    path:     /client
    defaults: { _controller: EasygestionBundle:Client:add }



easygestion_team:
    path:     /team
    defaults: { _controller: EasygestionBundle:Ia:team }

easygestion_projects:
    path:     /projects
    defaults: { _controller: EasygestionBundle:Ia:projects }